### ISSUE TITLE
No python3 register_users.py to open

### ISSUE THREAD

**Issue by epicolat** [saksham2410/telegram_scrapper_adder#1]
can you upload the python3 register_users.py to open pls there isn't .

**Comment by saksham2410** [comment]
Yes, I have taken it down because there was an issue with it leading to getting numbers banned. I will fix it in a day or two.

**Comment by epicolat** [comment]
i also have this issue when im using the last version of telehon

**Comment by epicolat** [comment]
Yes and do not use it for anything let it 1-2 hours before to use it

**Comment by epicolat** [comment]
i think that they started to ban api/hash when they look suspect that's why acc get instant ban

**Comment by epicolat** [comment]
Can you put again the files now that you know the problem ? thanks
